import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { LanguageProvider } from "../dictionaries/LanguageProvider";
import { getDictionary, Locale } from "../dictionaries/dictionaries";
import { Dictionary } from "../dictionaries/types";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params:{lang}
}: Readonly<{
  children: React.ReactNode;
  params: {lang:Locale}
}>) {

 const d  = await getDictionary(lang)
          
 

  return (
    <html lang="en">
      <body className={inter.className}>
        <LanguageProvider lang={d as Dictionary}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>{children}</ThemeProvider>
      </LanguageProvider>
      </body>
    </html>
  );
}
